token='MjcwMjkyODc5MjgzNDUzOTYy.DfB6Mw.Ws1UOVrqJs81uMkqjj9ObNEElnI'
fuhrer_id = 213970544083599374
bot_channel_id  = 453633789726425112
nl_scheldwoord_list = [
'zoetwatermosselaalskakker',
'aambeienbeffer',
'aambeienlikker',
'aambeienschoffelaar',
'aambeihaarwass',
'aangekleed nageboorte',
'aansteller',
'aap',
'aapjesviller',
'aapmens',
'aaprikaan',
'aardappelhoer',
'aardappelluis',
'aardbanaan (lief bedoeld)',
'aardgeest',
'aardpeer',
'aardpiraat',
'aardvarken',
'aardworm',
'aardworst',
'aars',
'aarsaap',
'aarsatleet',
'aarsbaard',
'aarsbaars',
'aarsbanaan',
'aarsbeer',
'aarsbeffer',
'aarselaar',
'aarsfreter',
'aarsgarnaal',
'aarshaar',
'aarshaarfohner',
'aarshaarknabbelaar',
'aarshaarluis',
'aarshaarverzamelaar',
'aarsketser',
'aarskind',
'aarsklodder',
'aarslander',
'aarslikker',
'aarslog',
'aarsneger',
'aarsridder',
'aarsmaad',
'aarsmade',
'aarsslijm',
'aarsvijand',
'aarsvis',
'aarsvochtlikkendevlooi',
'aarsworm',
'aartschurk'
'aarszweetsmurf',
'aasgier',
'abortuskind',
'absjaar',
'achterbaksestoephoer',
'achterlader',
'achterlijke',
'achterlijke zoetwatermossel',
'achterlijk gebakkie',
'achterpoter',
'achterbuurtfossiel ',
'acrobaat',
'adder',
'adderengebroedsels',
'addergebroed',
'afbak hoer',
'afgebakken frikandelhoofd',
'afgebefde legoman',
'afgedankte kuthoer',
'afgedankte pornofotograaf',
'afgedankte wcbril',
'afgebrokkelde teenheks',
'afgekakte muizenstront',
'afgekakte bosaap',
'afgekeurd komkommertijd product',
'afgekeurd-kutje',
'afgekeurd stuk kadaver',
'afgekeurde baby',
'afgekeurde kuttige flubberkont',
'afgekeurde straathoer',
'afgekloofde discohippie',
'afgekloven afwasborstel',
'afgekloven hamsterkut',
'afgelebberd brood',
'Afgelebberde flubberkut',
'afgelebberde kutcondoom',
'afgelebberde luldebehanger',
'afgelebberde negerinnentiet',
'afgelebberdekippencondoom',
'afgelebberde paardenkut',
'afgelebberde paardenpenis',
'afgelekte-koeiekak',
'afgelikteboterham',
'afgelikteboterhammenlikker',
'afgeliktehoerenmatras',
'afgeliktekuttekop',
'afgeliktelolly',
'afgelikte palingrukker',
'afgeliktestraatsnol',
'afgeliktstuksperma',
'afgelebberde paardenpik',
'afgelebberde penispijper',
'afgelebberde negerinnetieten',
'afgeneukte hondenbeffer',
'afgeneukte palingdrol',
'afgestudeerdemierenpijper',
'afgetrokken trektiet',
'afgetrokkenturk',
'afgezjabberde dicoslets',
'afrikaanse zeekomkommer',
'afstammeling',
'afstoot',
'aftreksel',
'afvallige',
'afvalturk',
'afzakker',
'afzuigroodkappie',
'akadildosnoeper',
'akrobaat',
'albinoreetkever',
'allesneuker',
'allochtoon',
'amateurklusser',
'amfitryon',
'amoebe',
'anaalaaiendebefkut',
'anaalafgezogen slettenbak',
'anaalgeneraal',
'anaalgarnaal',
'anaalist',
'anaaljager',
'anaalbkabaal',
'anaalkameraad',
'anaalkanaal',
'anaalkanibaal',
'anaalkoraal',
'anaalkanaalkannibaal',
'anaalkever',
'anaalnemende flubberkut',
'anaalpaal',
'anaalridder',
'anaaltoerist',
'anakoloet',
'anale arbeider',
'analfabeet',
'analist',
'anarchist',
'androchiem',
'anijsdrop',
'anita',
'anjer',
'ankerboer',
'anorexia slet',
'anthraciet',
'anthropopithecanthropus',
'anus',
'anus likkende frikandellen pijper',
'anusacrobaat',
'anusastronout',
'anusbikker',
'anusbuisvergruiser',
'anuscoureur',
'anusgezwel',
'anusgezicht',
'anusgitaar',
'anusgezwel',
'anushaargrabbelaar',
'anushaarslingeraar',
'anushaarvreter',
'anushaarknabbelaar',
'anushoofd',
'anushopper',
'anuskanaalninja',
'anuskringspiermusketierdier ',
'anuslikkendekontkever',
'anuslikker',
'anusnicht',
'anusontkalker',
'anuspapegaai',
'anuspenetreerder',
'anuspieper',
'anuspiloot',
'anuspiraat',
'anuspuntverknetteraar',
'anusreflector',
'anusridder',
'anussabbelaar',
'anussap-verzuring',
'anustoerist',
'anusuitscheiding',
'anusvreter',
'apache',
'apekloot',
'apekop',
'apekut',
'apegaper',
'apenbatser',
'apenflikerneuker',
'apenhaar',
'apenrukker',
'apeneuker',
'apewaffel',
'appel',
'appelflap',
'appelzwijn',
'argeologisch kontfossiel',
'armoedversprijder',
'armoedzaaier',
'arrefakker',
'asbak',
'arroganteklitzuigende-wrattenhoofd',
'asbestmuis',
'asfaltridder',
'asielzoeker',
'aso-big',
'asperge',
'asshole',
'augurk',
'augurkenneuker',
'augurkenturk',
'augurklul',
'autocraat',
'autodidact',
'autokraat',
'avocadoneuker',
'azteek']
